# Gunakan base image Python resmi (versi 3.10 atau lebih tinggi, slim untuk ukuran kecil)
FROM python:3.12-slim
# Setel direktori kerja di dalam container
WORKDIR /app
# Salin file requirements.txt ke dalam container
COPY requirements.txt .
# Instal dependensi yang tercantum di requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Salin seluruh isi direktori saat ini ke dalam container
COPY . .
# Expose port (FastAPI secara default 8000, Gradio akan mount di /gradio)
EXPOSE 8000
# Tentukan perintah untuk menjalankan aplikasi saat container dijalankan
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]